In [9]:
%matplotlib inline
import matplotlib_inline.backend_inline
matplotlib_inline.backend_inline.set_matplotlib_formats('svg')
import pandas as pd # import pandas
import numpy as np # import numpy
import matplotlib.pyplot as plt # import plotting module
import statistics
from IPython.display import set_matplotlib_formats # module for svg export
from filter import *

# set_matplotlib_formats('svg') # set export to svg fil
pd.set_option('display.max_rows', None)
cut_ratio = 0.05 # Values below 5% of mean value are simply cut from charts to make it more readable

### FILTERING ###
file = "uplink_messages.csv"
enable_filtering = True

config = {
    'node_id': [],
    'ap_id': [],
    'snr': [],
    'rssi': [],
    'spf': [],
    'frequency': [],
    'app_data': [],
    'recv_time_from': "",
    'recv_time_to': "2024-03-17 10:00"
}
operator = "AND"
### FILTERING ###

In [10]:
data = pd.read_csv(f"{file}", delimiter=',')

filtered_data = filter(data, config, operator)
                
display(filtered_data)

,id,app_data,snr,rssi,duty_cycle_remaining,is_primary,receive_time,seq,frequency,spf,...,airtime,coderate,bandwidth,msg_group_number,message_type_id,ap_id,node_id,dev_id,application_id,battery
0,1,Test2,9.0,-97.6,36000,t,2024-03-17 09:47:05.051,1,866100000,7,...,36,4/5,125000,0,1,123456,0rBU,38384,NaN,NaN
1,2,Test2,-10.6,-84.0,36000,t,2024-03-17 09:47:15.557,1,866100000,7,...,36,4/5,125000,0,1,123456,Oyxj,38385,NaN,NaN
2,3,Test2,9.7,-72.9,36000,t,2024-03-17 09:47:21.079,1,866100000,7,...,36,4/5,125000,0,1,123456,sNKE,38386,NaN,NaN
3,4,Test2,6.2,-95.9,36000,t,2024-03-17 09:49:04.668,2,866900000,12,...,803,4/5,125000,1,1,123456,0rBU,38387,NaN,NaN
4,5,Test2,0.0,-91.5,36000,t,2024-03-17 09:49:10.191,1,866100000,7,...,36,4/5,125000,0,1,123456,iMT8,38388,NaN,NaN
5,6,Test2,1.2,-85.1,36000,t,2024-03-17 09:49:15.2,2,866100000,7,...,36,4/5,125000,1,1,123456,Oyxj,38389,NaN,NaN
6,7,Test2,-19.3,-74.7,36000,t,2024-03-17 09:49:20.734,2,866100000,7,...,36,4/5,125000,1,1,123456,sNKE,38390,NaN,NaN
7,8,Test2,1.9,-98.2,36000,t,2024-03-17 09:51:05.308,3,866100000,7,...,36,4/5,125000,2,1,123456,0rBU,38391,NaN,NaN
8,9,Test2,-15.8,-90.9,36000,t,2024-03-17 09:51:10.305,2,866100000,7,...,36,4/5,125000,1,1,123456,iMT8,38392,NaN,NaN
9,10,Test2,-19.4,-86.1,36000,t,2024-03-17 09:51:15.312,3,866100000,7,...,36,4/5,125000,2,1,123456,Oyxj,38393,NaN,NaN
10,11,Test2,-10.9,-76.4,36000,t,2024-03-17 09:51:26.349,3,866100000,7,...,36,4/5,125000,2,1,123456,sNKE,38394,NaN,NaN
11,12,Test2,2.3,-98.6,36000,t,2024-03-17 09:53:05.435,4,866100000,7,...,36,4/5,125000,3,1,123456,0rBU,38395,NaN,NaN
12,13,Test2,-10.9,-90.3,36000,t,2024-03-17 09:53:10.438,3,866100000,7,...,36,4/5,125000,2,1,123456,iMT8,38396,NaN,NaN
13,14,Test2,-14.5,-87.0,36000,t,2024-03-17 09:53:15.443,4,866100000,7,...,36,4/5,125000,3,1,123456,Oyxj,38397,NaN,NaN
14,15,Test2,9.4,-82.5,36000,t,2024-03-17 09:53:20.963,1,866100000,7,...,36,4/5,125000,0,1,123456,Chxx,38398,NaN,NaN
15,16,Test2,-19.0,-77.9,36000,t,2024-03-17 09:53:26.485,4,866100000,7,...,36,4/5,125000,3,1,123456,sNKE,38399,NaN,NaN
16,17,Test2,-10.7,-96.9,36000,t,2024-03-17 09:55:05.06,5,866900000,12,...,803,4/5,125000,4,1,123456,0rBU,38400,NaN,NaN
17,18,Test2,-16.3,-87.7,36000,t,2024-03-17 09:55:10.086,4,866900000,12,...,803,4/5,125000,3,1,123456,iMT8,38401,NaN,NaN
18,19,Test2,6.3,-87.9,36000,t,2024-03-17 09:55:15.609,5,866100000,7,...,36,4/5,125000,4,1,123456,Oyxj,38402,NaN,NaN
19,20,Test2,-7.5,-82.6,36000,t,2024-03-17 09:55:21.126,2,866100000,7,...,36,4/5,125000,1,1,123456,Chxx,38403,NaN,NaN
20,21,Test2,-16.0,-79.4,36000,t,2024-03-17 09:55:26.651,5,866100000,7,...,36,4/5,125000,4,1,123456,sNKE,38404,NaN,NaN
21,22,Test2,-7.8,-99.2,36000,t,2024-03-17 09:57:05.696,6,866100000,7,...,36,4/5,125000,5,1,123456,0rBU,38405,NaN,NaN
22,23,Test2,-14.1,-89.1,36000,t,2024-03-17 09:57:10.695,5,866100000,7,...,36,4/5,125000,4,1,123456,iMT8,38406,NaN,NaN
23,24,Test2,1.8,-88.8,36000,t,2024-03-17 09:57:16.213,6,866100000,7,...,36,4/5,125000,5,1,123456,Oyxj,38407,NaN,NaN
24,25,Test2,-9.5,-82.8,36000,t,2024-03-17 09:57:21.733,3,866100000,7,...,36,4/5,125000,2,1,123456,Chxx,38408,NaN,NaN
25,26,Test2,-17.8,-80.8,36000,t,2024-03-17 09:57:27.259,6,866100000,7,...,36,4/5,125000,5,1,123456,sNKE,38409,NaN,NaN
26,27,Test2,5.1,-99.5,36000,t,2024-03-17 09:59:05.826,7,866100000,7,...,36,4/5,125000,6,1,123456,0rBU,38410,NaN,NaN
27,28,Test2,7.5,-88.5,36000,t,2024-03-17 09:59:10.831,6,866100000,7,...,36,4/5,125000,5,1,123456,iMT8,38411,NaN,NaN
28,29,Test2,0.8,-89.6,36000,t,2024-03-17 09:59:15.831,7,866100000,7,...,36,4/5,125000,6,1,123456,Oyxj,38412,NaN,NaN
29,30,Test2,-7.5,-83.0,36000,t,2024-03-17 09:59:21.358,4,866100000,7,...,36,4/5,125000,3,1,123456,Chxx,38413,NaN,NaN
30,31,Test2,0.5,-82.0,36000,t,2024-03-17 09:59:26.883,7,866100000,7,...,36,4/5,125000,6,1,123456,sNKE,38414,NaN,NaN

In [336]:
display(data)

,id,app_data,snr,rssi,duty_cycle_remaining,is_primary,receive_time,seq,frequency,spf,...,airtime,coderate,bandwidth,msg_group_number,message_type_id,ap_id,node_id,dev_id,application_id,battery
0,1,Test2,9.0,-97.6,36000,t,2024-03-17 09:47:05.051,1,866100000,7,...,36,4/5,125000,0,1,123456,0rBU,38384,NaN,NaN
1,2,Test2,-10.6,-84.0,36000,t,2024-03-17 09:47:15.557,1,866100000,7,...,36,4/5,125000,0,1,123456,Oyxj,38385,NaN,NaN
2,3,Test2,9.7,-72.9,36000,t,2024-03-17 09:47:21.079,1,866100000,7,...,36,4/5,125000,0,1,123456,sNKE,38386,NaN,NaN
3,4,Test2,6.2,-95.9,36000,t,2024-03-17 09:49:04.668,2,866900000,12,...,803,4/5,125000,1,1,123456,0rBU,38387,NaN,NaN
4,5,Test2,0.0,-91.5,36000,t,2024-03-17 09:49:10.191,1,866100000,7,...,36,4/5,125000,0,1,123456,iMT8,38388,NaN,NaN
5,6,Test2,1.2,-85.1,36000,t,2024-03-17 09:49:15.2,2,866100000,7,...,36,4/5,125000,1,1,123456,Oyxj,38389,NaN,NaN
6,7,Test2,-19.3,-74.7,36000,t,2024-03-17 09:49:20.734,2,866100000,7,...,36,4/5,125000,1,1,123456,sNKE,38390,NaN,NaN
7,8,Test2,1.9,-98.2,36000,t,2024-03-17 09:51:05.308,3,866100000,7,...,36,4/5,125000,2,1,123456,0rBU,38391,NaN,NaN
8,9,Test2,-15.8,-90.9,36000,t,2024-03-17 09:51:10.305,2,866100000,7,...,36,4/5,125000,1,1,123456,iMT8,38392,NaN,NaN
9,10,Test2,-19.4,-86.1,36000,t,2024-03-17 09:51:15.312,3,866100000,7,...,36,4/5,125000,2,1,123456,Oyxj,38393,NaN,NaN
10,11,Test2,-10.9,-76.4,36000,t,2024-03-17 09:51:26.349,3,866100000,7,...,36,4/5,125000,2,1,123456,sNKE,38394,NaN,NaN
11,12,Test2,2.3,-98.6,36000,t,2024-03-17 09:53:05.435,4,866100000,7,...,36,4/5,125000,3,1,123456,0rBU,38395,NaN,NaN
12,13,Test2,-10.9,-90.3,36000,t,2024-03-17 09:53:10.438,3,866100000,7,...,36,4/5,125000,2,1,123456,iMT8,38396,NaN,NaN
13,14,Test2,-14.5,-87.0,36000,t,2024-03-17 09:53:15.443,4,866100000,7,...,36,4/5,125000,3,1,123456,Oyxj,38397,NaN,NaN
14,15,Test2,9.4,-82.5,36000,t,2024-03-17 09:53:20.963,1,866100000,7,...,36,4/5,125000,0,1,123456,Chxx,38398,NaN,NaN
15,16,Test2,-19.0,-77.9,36000,t,2024-03-17 09:53:26.485,4,866100000,7,...,36,4/5,125000,3,1,123456,sNKE,38399,NaN,NaN
16,17,Test2,-10.7,-96.9,36000,t,2024-03-17 09:55:05.06,5,866900000,12,...,803,4/5,125000,4,1,123456,0rBU,38400,NaN,NaN
17,18,Test2,-16.3,-87.7,36000,t,2024-03-17 09:55:10.086,4,866900000,12,...,803,4/5,125000,3,1,123456,iMT8,38401,NaN,NaN
18,19,Test2,6.3,-87.9,36000,t,2024-03-17 09:55:15.609,5,866100000,7,...,36,4/5,125000,4,1,123456,Oyxj,38402,NaN,NaN
19,20,Test2,-7.5,-82.6,36000,t,2024-03-17 09:55:21.126,2,866100000,7,...,36,4/5,125000,1,1,123456,Chxx,38403,NaN,NaN
20,21,Test2,-16.0,-79.4,36000,t,2024-03-17 09:55:26.651,5,866100000,7,...,36,4/5,125000,4,1,123456,sNKE,38404,NaN,NaN
21,22,Test2,-7.8,-99.2,36000,t,2024-03-17 09:57:05.696,6,866100000,7,...,36,4/5,125000,5,1,123456,0rBU,38405,NaN,NaN
22,23,Test2,-14.1,-89.1,36000,t,2024-03-17 09:57:10.695,5,866100000,7,...,36,4/5,125000,4,1,123456,iMT8,38406,NaN,NaN
23,24,Test2,1.8,-88.8,36000,t,2024-03-17 09:57:16.213,6,866100000,7,...,36,4/5,125000,5,1,123456,Oyxj,38407,NaN,NaN
24,25,Test2,-9.5,-82.8,36000,t,2024-03-17 09:57:21.733,3,866100000,7,...,36,4/5,125000,2,1,123456,Chxx,38408,NaN,NaN
25,26,Test2,-17.8,-80.8,36000,t,2024-03-17 09:57:27.259,6,866100000,7,...,36,4/5,125000,5,1,123456,sNKE,38409,NaN,NaN
26,27,Test2,5.1,-99.5,36000,t,2024-03-17 09:59:05.826,7,866100000,7,...,36,4/5,125000,6,1,123456,0rBU,38410,NaN,NaN
27,28,Test2,7.5,-88.5,36000,t,2024-03-17 09:59:10.831,6,866100000,7,...,36,4/5,125000,5,1,123456,iMT8,38411,NaN,NaN
28,29,Test2,0.8,-89.6,36000,t,2024-03-17 09:59:15.831,7,866100000,7,...,36,4/5,125000,6,1,123456,Oyxj,38412,NaN,NaN
29,30,Test2,-7.5,-83.0,36000,t,2024-03-17 09:59:21.358,4,866100000,7,...,36,4/5,125000,3,1,123456,Chxx,38413,NaN,NaN
30,31,Test2,0.5,-82.0,36000,t,2024-03-17 09:59:26.883,7,866100000,7,...,36,4/5,125000,6,1,123456,sNKE,38414,NaN,NaN
31,32,Test2,4.7,-97.9,36000,t,2024-03-17 10:01:05.457,8,866900000,12,...,803,4/5,125000,7,1,123456,0rBU,38415,NaN,NaN
32,33,Test2,-14.9,-87.9,36000,t,2024-03-17 10:01:10.983,7,866100000,7,...,36,4/5,125000,6,1,123456,iMT8,38416,NaN,NaN
33,34,Test2,-12.5,-90.4,36000,t,2024-03-17 10:01:16.509,8,866100000,7,...,36,4/5,125000,7,1,123456,Oyxj,38417,NaN,NaN
34,35,Test2,-14.9,-85.3,36000,t,2024-03-17 10:03:05.612,8,866900000,12,...,803,4/5,125000,7,1,123456,iMT8,38418,NaN,NaN
35,36,Test2,-13.9,-91.1,36000,t,2024-03-17 10:03:11.134,9,866100000,7,...,36,4/5,125000,8,1,123456,Oyxj,38419,NaN,NaN
36,37,Test2,7.0,-83.7,36000,t,2024-03-17 10:03:16.667,5,866100000,7,...,36,4/5,125000,4,1,123456,Chxx,38420,NaN,NaN
37,38,Test2,8.9,-84.3,36000,t,2024-03-17 10:03:22.186,8,866100000,7,...,36,4/5,125000,7,1,123456,sNKE,38421,NaN,NaN
38,39,Test2,-9.9,-86.7,36000,t,2024-03-17 10:05:06.246,9,866100000,7,...,36,4/5,125000,8,1,123456,iMT8,38422,NaN,NaN
39,40,Test2,-8.4,-91.9,36000,t,2024-03-17 10:05:11.77,10,866100000,7,...,36,4/5,125000,9,1,123456,Oyxj,38423,NaN,NaN
40,41,Test2,-17.9,-84.2,36000,t,2024-03-17 10:05:16.776,6,866100000,7,...,36,4/5,125000,5,1,123456,Chxx,38424,NaN,NaN
41,42,Test2,5.7,-85.3,36000,t,2024-03-17 10:05:22.305,9,866100000,7,...,36,4/5,125000,8,1,123456,sNKE,38425,NaN,NaN
42,43,Test2,-12.2,-99.9,36000,t,2024-03-17 10:07:06.332,9,866100000,7,...,36,4/5,125000,8,1,123456,0rBU,38426,NaN,NaN
43,44,Test2,-8.5,-92.6,36000,t,2024-03-17 10:07:11.338,11,866100000,7,...,36,4/5,125000,10,1,123456,Oyxj,38427,NaN,NaN
44,45,Test2,-11.4,-84.6,36000,t,2024-03-17 10:07:16.345,7,866100000,7,...,36,4/5,125000,6,1,123456,Chxx,38428,NaN,NaN
45,46,Test2,0.3,-86.3,36000,t,2024-03-17 10:07:21.871,10,866100000,7,...,36,4/5,125000,9,1,123456,sNKE,38429,NaN,NaN
46,47,Test2,-18.1,-85.5,36000,t,2024-03-17 10:09:06.503,10,866100000,7,...,36,4/5,125000,9,1,123456,iMT8,38430,NaN,NaN
47,48,Test2,8.5,-93.3,36000,t,2024-03-17 10:09:11.507,12,866100000,7,...,36,4/5,125000,11,1,123456,Oyxj,38431,NaN,NaN
48,49,Test2,-10.8,-85.2,36000,t,2024-03-17 10:09:16.513,8,866100000,7,...,36,4/5,125000,7,1,123456,Chxx,38432,NaN,NaN
49,50,Test2,-7.7,-87.2,36000,t,2024-03-17 10:09:22.029,11,866100000,7,...,36,4/5,125000,10,1,123456,sNKE,38433,NaN,NaN
50,51,Test2,-7.5,-83.1,36000,t,2024-03-17 10:11:06.13,11,866900000,12,...,803,4/5,125000,10,1,123456,iMT8,38434,NaN,NaN
51,52,Test2,-10.2,-93.9,36000,t,2024-03-17 10:11:11.652,13,866100000,7,...,36,4/5,125000,12,1,123456,Oyxj,38435,NaN,NaN
52,53,Test2,-18.3,-85.8,36000,t,2024-03-17 10:11:16.651,9,866100000,7,...,36,4/5,125000,8,1,123456,Chxx,38436,NaN,NaN

In [332]:
if attack == "replay":
    try:
        del filtered_data['id']
        del filtered_data['msg_group_number']
        del filtered_data['is_primary']
        del filtered_data['message_type_id']
        del filtered_data['coderate']
        del filtered_data['bandwidth']
        del filtered_data['duty_cycle_remaining']
        del filtered_data['seq']
        del filtered_data['power']
        del filtered_data['airtime']
        del filtered_data['application_id']
        del filtered_data['battery']
        del filtered_data['app_data']
        del filtered_data['dev_id']
    except KeyError:
        print('Columns have already been removed')

In [333]:
sorted_data = filtered_data.sort_values(by='receive_time', ascending=True)
display(sorted_data)

   snr  rssi             receive_time  frequency  spf   ap_id node_id
0  9.0 -97.6  2024-03-17 09:47:05.051  866100000    7  123456    0rBU